version: '3'

services:
  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  mongo:
    image: "mongo:4.4"
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
